# Generated by Django 3.2.2 on 2021-05-15 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinta_nivelmodel',
            name='nivelModel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='administrador.nivelmodel', verbose_name='Nivel'),
        ),
    ]
