# Generated by Django 3.2.2 on 2021-05-16 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrador', '0002_alter_cinta_nivelmodel_nivelmodel'),
        ('dojo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipanteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('NumParticipante', models.IntegerField(verbose_name='NumParticipante')),
                ('FechaNacimiento', models.DateField(verbose_name='Fecha Nacimiento')),
                ('Edad', models.IntegerField(verbose_name='Edad')),
                ('Peso', models.IntegerField(verbose_name='Peso')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Creación')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Actualización')),
                ('clasificacionKata', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='clasificacionKata', to='administrador.clasificacionkaratemodel', verbose_name='NivelKata')),
                ('clasificacionKumite', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='clasificacionKumite', to='administrador.clasificacionkaratemodel', verbose_name='NivelKumite')),
                ('dojoModel', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dojo.dojomodel', verbose_name='Dojo')),
                ('generoModel', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='administrador.generomodel', verbose_name='Genero')),
                ('nivelKata', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='nivelKata', to='administrador.nivelmodel', verbose_name='NivelKata')),
                ('nivelKumite', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='nivelKumite', to='administrador.nivelmodel', verbose_name='NivelKumite')),
            ],
            options={
                'verbose_name': 'Dojo',
                'verbose_name_plural': 'Dojos',
                'ordering': ['-create'],
            },
        ),
    ]
