# Generated by Django 3.2.2 on 2021-05-29 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0002_alter_cinta_nivelmodel_nivelmodel'),
        ('participante', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantemodel',
            name='NumParticipante',
            field=models.IntegerField(verbose_name='Número participante'),
        ),
        migrations.AlterField(
            model_name='participantemodel',
            name='clasificacionKata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='clasificacionKata', to='administrador.clasificacionkaratemodel', verbose_name='Clasificación Kata'),
        ),
        migrations.AlterField(
            model_name='participantemodel',
            name='clasificacionKumite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='clasificacionKumite', to='administrador.clasificacionkaratemodel', verbose_name='Clasificacón Kumite'),
        ),
        migrations.AlterField(
            model_name='participantemodel',
            name='nivelKata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='nivelKata', to='administrador.nivelmodel', verbose_name='Nivel de Kata'),
        ),
        migrations.AlterField(
            model_name='participantemodel',
            name='nivelKumite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='nivelKumite', to='administrador.nivelmodel', verbose_name='Nivel de Kumite'),
        ),
    ]
