# Generated by Django 3.2.2 on 2021-05-16 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrador', '0002_alter_cinta_nivelmodel_nivelmodel'),
        ('dojo', '0001_initial'),
        ('participante', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante_modalidadmodel',
            name='participanteModel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='participante.participantemodel', verbose_name='Participante'),
        ),
        migrations.AddField(
            model_name='equipomodel',
            name='clasificacionModel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='administrador.clasificacionkaratemodel', verbose_name='Clasificacion'),
        ),
        migrations.AddField(
            model_name='equipomodel',
            name='dojoModel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dojo.dojomodel', verbose_name='Dojo'),
        ),
    ]
