# Generated by Django 3.2.2 on 2021-05-19 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dojomodel',
            options={'verbose_name': 'Dojo', 'verbose_name_plural': 'Dojos'},
        ),
    ]
