# Generated by Django 3.2.2 on 2021-05-19 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0003_alter_dojomodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dojomodel',
            options={},
        ),
    ]
